
services:
  server1:
    build: ./server1
    container_name: server1

  server2:
    build: ./server2
    container_name: server2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - server1
      - server2
